name: MinKinD Smoke Test

on:
  push:
    branches: [ master ]

jobs:
  e2e-tests:
    name: e2e tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false # Keep running if one leg fails.
      matrix:
        k8s-version:
        - v1.17.11
        - v1.18.8
        - v1.19.1

        repo:
        - networking
        - serving
        - eventing

        # Map between K8s and KinD versions.
        # This is attempting to make it a bit clearer what's being tested.
        # See: https://github.com/kubernetes-sigs/kind/releases/tag/v0.9.0
        include:
        - k8s-version: v1.17.11
          kind-version: v0.9.0
        - k8s-version: v1.18.8
          kind-version: v0.9.0
        - k8s-version: v1.19.1
          kind-version: v0.9.0

        - repo: serving
          importpath: foo
        - repo: serving
          importpath: bar
        - repo: eventing
          importpath: bar
        - repo: networking
          importpath: baz

    steps:
    - name: Install KinD
      run: |
        echo ${{ matrix.kind-version }} ${{ matrix.repo }} ${{ matrix.importpath }}
