# Copyright 2020 The Knative Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Auto Updates

on:
  push:
    branches: [ 'master' ]

jobs:
  update-deps:
    name: Update Deps and Codegen
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false # Keep running if one leg fails.
      matrix:
        name: 
        - 'knative/pkg'

    env:
      GO111MODULE: on

    steps:

    - name: Set up Go 1.15.x
      uses: actions/setup-go@v2
      with:
        go-version: 1.15.x
      id: go

    - name: Check out code onto GOPATH
      uses: actions/checkout@v2
      with:
        repository: ${{ matrix.name }}

    - name: Install Dependencies
      run: |
        cd $(mktemp -d)
        go get github.com/google/ko/cmd/ko
        go get github.com/google/licenseclassifier
        go get github.com/google/go-licenses

    - name: Update Deps and Codegen
      shell: bash
      run: |
        # Determine the name of the go module.
        export MODULE_NAME=$(go mod graph | cut -d' ' -f 1 | grep -v '@' | head -1)

        # TODO(mattmoor): Move this into `./hack/update-codegen.sh`
        TMP_DIR="$(mktemp -d)"
        export GOPATH=${GOPATH:-${TMP_DIR}}
        export PATH="${PATH}:${TMP_DIR}/bin"
        TMP_REPO_PATH="${TMP_DIR}/src/${MODULE_NAME}"
        mkdir -p "$(dirname "${TMP_REPO_PATH}")" && ln -s "${GITHUB_WORKSPACE}" "${TMP_REPO_PATH}"

        ./hack/update-deps.sh --upgrade
        # We may pull in code-generator updates, or not have generated code.
        [[ ! -f hack/update-codegen.sh ]] || ./hack/update-codegen.sh

        # If we don't run this before the "git diff-index" it seems to list
        # every file that's been touched by codegen.
        git status

        echo "::set-env name=create_pr::false"
        for x in $(git diff-index --name-only HEAD --); do
          if [ "$(basename $x)" = "go.mod" ]; then
            continue
          elif [ "$(basename $x)" = "go.sum" ]; then
            continue
          elif [ "$(basename $x)" = "modules.txt" ]; then
            continue
          fi
          echo "Found non-module diff: $x"
          echo "::set-env name=create_pr::true"
          break
        done

    - name: Next
      shell: bash
      if: env.create_pr == 'true'
      run: |
        echo Hello there
        git diff
        exit 1
