name: buildx test

on:
  push:
    branches: [ master ]

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: tektoncd/pipeline

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Docker login
        run: |
          docker login -u mattmoor -p ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build base
        run: |
          docker buildx build \
            --platform ${{ steps.buildx.outputs.platforms }} \
            --file ./images/Dockerfile --tag docker.io/mattmoor/testing:latest --push .
