name: CI

on:

  push:
    branches: [ 'master' ]

#  schedule:
#  - cron: '* * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Determine the action link
        run: |
          echo GITHUB_WORKFLOW_URL=https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID

          # Dump the environment to see what else we find
          env

      - name: Post to slack
        uses: rtCamp/action-slack-notify@v2.1.0
        env:
          SLACK_ICON: http://github.com/mattmoor-sockpuppet.png?size=48
          SLACK_USERNAME: sockpuppet
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

          SLACK_CHANNEL: '@mattmoor'
          SLACK_COLOR: '#3278BD'
          MSG_MINIMAL: 'true'
          SLACK_TITLE: put-your-title-here
          SLACK_MESSAGE: |
            This is a test of minimal messages.
