name: CI

on:

  push:
    branches: [ 'master' ]

#  schedule:
#  - cron: '* * * * *'

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      matrix-include: ${{ steps.load-matrix.outputs.matrix-include }}
    steps:
    - name: Check out code onto GOPATH
      uses: actions/checkout@v2
    - name: Set up Go 1.15.x
      uses: actions/setup-go@v2
      with:
        go-version: 1.15.x

    - id: load-matrix
      run: |
        go get github.com/bronze1man/yaml2json
        
        cat ${GITHUB_WORKSPACE}/repos.yaml | yaml2json
        
        echo "::set-output name=matrix-include::$(cat ${GITHUB_WORKSPACE}/repos.yaml | yaml2json)"

  build:
    needs: job1
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false # Keep running if one leg fails.
      matrix:
        name:
        # Only run a subset
        - 'knative/pkg'
        - 'knative/caching'
        - 'knative/networking'
        - 'knative/serving'
        - 'knative/eventing'
        include: ${{fromJson(needs.job1.outputs.matrix-include)}}

    steps:
    - name: Copy Actions
      shell: bash
      run: |
        echo "${{ matrix.name }} has channel ${{ matrix.channel }}"
