name: CI

on:
  schedule:
  - cron: '* * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Post to slack
        uses: rtCamp/action-slack-notify@v2.1.0
        env:
          SLACK_CHANNEL: '@mattmoor'
          SLACK_COLOR: '#3278BD'
          SLACK_ICON: http://github.com/mattmoor-sockpuppet.png?size=48
          SLACK_MESSAGE: 'Test DMs'
          SLACK_TITLE: Blah dee blah
          SLACK_USERNAME: sockpuppet
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
