name: CI

on:

  push:
    branches: [ 'master' ]

#  schedule:
#  - cron: '* * * * *'

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      matrix-include: ${{ steps.load-matrix.outputs.matrix-include }}
    steps:
    - name: Check out code onto GOPATH
      uses: actions/checkout@v2
    - name: Set up Go 1.15.x
      uses: actions/setup-go@v2
      with:
        go-version: 1.15.x

    - id: load-matrix
      run: |
        go get github.com/bronze1man/yaml2json
        
        cat ${GITHUB_WORKSPACE}/.github/workflows/main.yml | yaml2json
        
        echo "::set-output name=matrix-include::$(cat ${GITHUB_WORKSPACE}/.github/workflows/main.yml | yaml2json)"

  build:
    needs: job1
    runs-on: ubuntu-latest

    steps:
      - name: Dump stuff
        run: |
          
          cat | python -mjson.tool <<EOF
          ${{ needs.job1.outputs.include-matrix }}
          EOF
          
          
          # Dump things to check what's available
          echo '::group::github'
          cat | python -mjson.tool <<EOF
          ${{ toJson(github) }}
          EOF
          echo '::endgroup::'

          echo '::group::env'
          cat | python -mjson.tool <<EOF
          ${{ toJson(env) }}
          EOF
          echo '::endgroup::'

          echo '::group:: job'
          cat | python -mjson.tool <<EOF
          ${{ toJson(job) }}
          EOF
          echo '::endgroup::'

          echo '::group:: steps'
          cat | python -mjson.tool <<EOF
          ${{ toJson(steps) }}
          EOF
          echo '::endgroup::'

      - name: Post to slack
        uses: rtCamp/action-slack-notify@v2.1.0
        env:
          SLACK_ICON: http://github.com/mattmoor-sockpuppet.png?size=48
          SLACK_USERNAME: sockpuppet
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

          SLACK_CHANNEL: '@mattmoor'
          SLACK_COLOR: '#3278BD'
          MSG_MINIMAL: 'true'
          SLACK_TITLE: put-your-title-here
          SLACK_MESSAGE: |
            You can see this run here: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
