name: MinKinD Smoke Test

on:
  push:
    branches: [ master ]

jobs:
  e2e-tests:
    name: e2e tests
    runs-on: ubuntu-latest

    steps:
    - name: Install KinD
      timeout-minutes: 1
      run: |
        echo Hi
        sleep 60
        echo Bye
